FROM python:3.12.3-slim


WORKDIR /app


COPY main.py /app/
COPY random_paragraph.txt /app/

RUN pip install --no-cache-dir nltk
RUN python -c "import nltk; nltk.download('punkt')"

CMD ["python", "main.py"]